package com.recetea.core.user.domain;

/**
 * Strongly-typed identifier for a {@code User} aggregate. Lives in
 * {@code com.recetea.core.user.domain} (not {@code .vo}) because it's a
 * cross-cutting handle: the recipe + social bounded contexts both reference
 * users by id, so this is the one user-domain type re-exported through
 * {@code module-info.java}.
 *
 * <p>Compact-constructor invariant: positive value only — PostgreSQL's
 * {@code users.user_id GENERATED BY DEFAULT AS IDENTITY} starts at {@code 1}.
 *
 * <p><b>ES — </b>Identificador fuertemente tipado para un agregado
 * {@code User}. Vive en {@code com.recetea.core.user.domain} (no en
 * {@code .vo}) porque es un manejador transversal: los contextos delimitados
 * de recetas y social referencian usuarios por id, así que éste es el único
 * tipo del dominio de usuario reexportado a través de
 * {@code module-info.java}.
 *
 * <p>Invariante del constructor compacto: solo valores positivos —
 * {@code users.user_id GENERATED BY DEFAULT AS IDENTITY} de PostgreSQL empieza
 * en {@code 1}.
 */
public record UserId(int value) {
    public UserId {
        if (value <= 0) throw new IllegalArgumentException("UserId must be positive.");
    }
}
