package com.recetea.core.recipe.domain.vo;

/**
 * Strongly-typed identifier for a {@code Recipe} aggregate. Wrapping the database
 * surrogate key in a record prevents accidental mix-ups in method signatures —
 * the compiler rejects passing an {@code IngredientId} where a {@code RecipeId}
 * is expected, even though both wrap an {@code int} at runtime.
 *
 * <p>Compact-constructor invariant: the value must be positive. {@code 0} and
 * negatives are rejected because PostgreSQL's {@code GENERATED BY DEFAULT AS IDENTITY}
 * starts at {@code 1}; any non-positive value indicates a programming mistake
 * (uninitialised default, signed-int overflow) rather than legitimate persistence state.
 *
 * <p><b>ES — </b>Identificador fuertemente tipado para un agregado {@code Recipe}.
 * Envolver la clave subrogada de la base de datos en un record evita mezclas
 * accidentales en las firmas de método — el compilador rechaza pasar un
 * {@code IngredientId} donde se espera un {@code RecipeId}, aunque ambos
 * envuelvan un {@code int} en tiempo de ejecución.
 *
 * <p>Invariante del constructor compacto: el valor debe ser positivo. {@code 0}
 * y los negativos se rechazan porque {@code GENERATED BY DEFAULT AS IDENTITY}
 * de PostgreSQL empieza en {@code 1}; cualquier valor no positivo indica un
 * error de programación (valor por defecto sin inicializar, desbordamiento de
 * int con signo) y no un estado legítimo de persistencia.
 */
public record RecipeId(int value) {
    public RecipeId {
        if (value <= 0) throw new IllegalArgumentException("RecipeId must be positive.");
    }
}
