package com.recetea.infrastructure.persistence.recipe.jdbc.repositories;

import com.recetea.core.recipe.application.ports.in.dto.RecipeSummaryResponse;
import com.recetea.core.shared.domain.PageRequest;
import com.recetea.core.shared.domain.PageResponse;
import com.recetea.core.recipe.domain.Category;
import com.recetea.core.recipe.domain.Difficulty;
import com.recetea.core.recipe.domain.Recipe;
import com.recetea.core.recipe.domain.RecipeIngredient;
import com.recetea.core.recipe.domain.RecipeMedia;
import com.recetea.core.recipe.domain.RecipeStep;
import com.recetea.core.recipe.domain.vo.*;
import com.recetea.core.user.domain.UserId;
import com.recetea.infrastructure.persistence.recipe.jdbc.JdbcTransactionManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.recetea.core.recipe.domain.Rating;
import com.recetea.core.recipe.domain.vo.Score;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class JdbcRecipeRepositoryTest extends BaseRepositoryTest {

    private JdbcRecipeRepository repository;
    private JdbcTransactionManager transactionManager;

    @BeforeEach
    void setUp() throws SQLException {
        transactionManager = new JdbcTransactionManager(dataSource);
        repository = new JdbcRecipeRepository(transactionManager, metricsPort);
        seedReferenceData();
    }

    private void seedReferenceData() throws SQLException {
        try (Connection conn = dataSource.getConnection(); Statement st = conn.createStatement()) {
            st.execute("INSERT INTO users (user_id, username, email, password_hash) OVERRIDING SYSTEM VALUE VALUES (1, 'test', 'test@test.com', 'hash')");
            st.execute("INSERT INTO users (user_id, username, email, password_hash) OVERRIDING SYSTEM VALUE VALUES (2, 'voter1', 'voter1@test.com', 'hash')");
            st.execute("INSERT INTO users (user_id, username, email, password_hash) OVERRIDING SYSTEM VALUE VALUES (3, 'voter2', 'voter2@test.com', 'hash')");
            st.execute("INSERT INTO categories (category_id, name) OVERRIDING SYSTEM VALUE VALUES (1, 'TestCat')");
            st.execute("INSERT INTO difficulties (difficulty_id, difficulty_level) OVERRIDING SYSTEM VALUE VALUES (1, 'Easy')");
            st.execute("INSERT INTO ingredient_categories (ingredient_category_id, name) OVERRIDING SYSTEM VALUE VALUES (1, 'TestIngCat')");
            st.execute("INSERT INTO unit_measures (unit_id, name, abbreviation) OVERRIDING SYSTEM VALUE VALUES (1, 'Gram', 'g')");
            st.execute("INSERT INTO ingredients (ingredient_id, ingredient_category_id, name) OVERRIDING SYSTEM VALUE VALUES " +
                    "(1, 1, 'Ing1'), (2, 1, 'Ing2'), (3, 1, 'Ing3'), (4, 1, 'Ing4')");
        }
    }

    private Recipe buildRecipe() {
        return new Recipe(
                new UserId(1),
                new Category(new CategoryId(1), "TestCat"),
                new Difficulty(new DifficultyId(1), "Easy"),
                "Test Recipe", "Test description",
                new PreparationTime(30),
                new Servings(2)
        );
    }

    @Test
    @DisplayName("Should persist recipe and components within the same transaction")
    void save_ShouldPersistRecipeAndComponentsUnderSameTransaction() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(
                        new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.valueOf(500))
                ))
                .syncSteps(List.of(new RecipeStep(1, "Cook everything")));

        RecipeId savedId = transactionManager.execute(() -> repository.save(recipe));

        assertNotNull(savedId, "ID should be generated by the database");
        int id = savedId.value();
        assertEquals(1, queryCount("SELECT count(*) FROM recipes WHERE recipe_id = " + id), "Recipe should exist in the database");
        assertEquals(1, queryCount("SELECT count(*) FROM recipe_ingredients WHERE recipe_id = " + id), "Ingredient should have been persisted");
    }

    @Test
    @DisplayName("Should cascade delete without leaving orphaned records")
    void delete_ShouldCascadeDeleteWithoutOrphanedRecords() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(
                        new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.valueOf(100))
                ))
                .syncSteps(List.of(new RecipeStep(1, "Single step")));

        RecipeId savedId = transactionManager.execute(() -> repository.save(recipe));
        int id = savedId.value();

        transactionManager.execute(() -> repository.delete(savedId));

        assertEquals(0, queryCount("SELECT count(*) FROM recipes WHERE recipe_id = " + id));
        assertEquals(0, queryCount("SELECT count(*) FROM recipe_ingredients WHERE recipe_id = " + id));
        assertEquals(0, queryCount("SELECT count(*) FROM steps WHERE recipe_id = " + id));
    }

    @Test
    @DisplayName("Smart diff should granularly update, insert, and delete ingredients")
    void testSmartDiffingLogic() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(
                        new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.valueOf(100)),
                        new RecipeIngredient(new IngredientId(2), new UnitId(1), BigDecimal.valueOf(200)),
                        new RecipeIngredient(new IngredientId(3), new UnitId(1), BigDecimal.valueOf(300))
                ))
                .syncSteps(List.of(new RecipeStep(1, "Initial step")));
        RecipeId savedId = transactionManager.execute(() -> repository.save(recipe));

        int recipeId = savedId.value();

        Recipe toUpdate = repository.findById(savedId).orElseThrow()
                .syncIngredients(List.of(
                        new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.valueOf(100)),
                        new RecipeIngredient(new IngredientId(2), new UnitId(1), BigDecimal.valueOf(250)),
                        new RecipeIngredient(new IngredientId(4), new UnitId(1), BigDecimal.valueOf(400))
                ));
        transactionManager.execute(() -> repository.update(toUpdate));

        assertEquals(BigDecimal.valueOf(100).setScale(2), queryQuantity(recipeId, 1), "Ingredient 1 unchanged");
        assertEquals(BigDecimal.valueOf(250).setScale(2), queryQuantity(recipeId, 2), "Ingredient 2 updated");
        assertNull(queryQuantity(recipeId, 3), "Ingredient 3 deleted");
        assertEquals(BigDecimal.valueOf(400).setScale(2), queryQuantity(recipeId, 4), "Ingredient 4 added");
    }

    @Test
    @DisplayName("findById should hydrate the aggregate's ratings list")
    void findById_ShouldHydrateRatingsList() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId recipeId = transactionManager.execute(() -> repository.save(recipe));

        seedRating(new UserId(2), recipeId, 4);
        seedRating(new UserId(3), recipeId, 5);

        Recipe loaded = repository.findById(recipeId).orElseThrow();

        assertEquals(2, loaded.getRatings().size(), "Should hydrate exactly 2 ratings");
        assertTrue(loaded.getRatings().stream()
                .anyMatch(r -> r.userId().equals(new UserId(2)) && r.score().value() == 4));
        assertTrue(loaded.getRatings().stream()
                .anyMatch(r -> r.userId().equals(new UserId(3)) && r.score().value() == 5));
    }

    @Test
    @DisplayName("updateSocialMetrics should persist domain-computed metrics")
    void updateSocialMetrics_ShouldPersistDomainMetrics() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId recipeId = transactionManager.execute(() -> repository.save(recipe));

        transactionManager.execute(() ->
                repository.updateSocialMetrics(recipeId, new BigDecimal("5.00"), 1));

        Recipe loaded = repository.findById(recipeId).orElseThrow();
        assertEquals(1, loaded.getTotalRatings(), "total_ratings should be 1 after synchronization");
        assertEquals(0, new BigDecimal("5.00").compareTo(loaded.getAverageScore()),
                "average_score should reflect the score of the inserted rating");
    }

    @Test
    @DisplayName("update should persist the new rating + recomputed social metrics after addRating")
    void update_ShouldPersistMetrics_AfterAddRating() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId recipeId = transactionManager.execute(() -> repository.save(recipe));

        Recipe loaded = repository.findById(recipeId).orElseThrow()
                .addRating(new UserId(2), new Score(4), "Very good recipe");

        transactionManager.execute(() -> repository.update(loaded));

        BigDecimal persistedScore = queryBigDecimal(
                "SELECT average_score FROM recipes WHERE recipe_id = " + recipeId.value());
        int persistedTotal = queryCount(
                "SELECT total_ratings FROM recipes WHERE recipe_id = " + recipeId.value());
        int ratingRows = queryCount(
                "SELECT count(*) FROM ratings WHERE recipe_id = " + recipeId.value());

        assertEquals(0, new BigDecimal("4.00").compareTo(persistedScore),
                "average_score should be 4.00 (single vote of 4)");
        assertEquals(1, persistedTotal, "total_ratings should be 1");
        assertEquals(1, ratingRows, "Rating should have been inserted into the ratings table");
    }

    @Test
    @DisplayName("update should keep the ratings count stable when only metadata changes (idempotent upsert)")
    void update_ShouldNotChangeRatingCount_OnMetadataOnlyEdit() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId savedId = transactionManager.execute(() -> repository.save(recipe));

        seedRating(new UserId(2), savedId, 5);

        // Title-only edit. The repository's saveRatings call is unconditional but idempotent —
        // the ratings list rehydrated from the DB is upserted back unchanged, so the row count
        // stays at 1.
        Recipe loaded = repository.findById(savedId).orElseThrow().withTitle("Updated Title");
        transactionManager.execute(() -> repository.update(loaded));

        assertEquals(1, queryCount("SELECT count(*) FROM ratings WHERE recipe_id = " + savedId.value()),
                "Rating count should not change on metadata-only update");
    }

    @Test
    @DisplayName("findAllSummaries should read average_score and total_ratings from denormalized columns")
    void findAllSummaries_ShouldReadFromDenormalizedColumns() {
        Recipe recipeA = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step A")));
        RecipeId idA = transactionManager.execute(() -> repository.save(recipeA));
        // Push domain-computed metrics to the denormalized columns (simulates two ratings: avg 4.50)
        transactionManager.execute(() ->
                repository.updateSocialMetrics(idA, new BigDecimal("4.50"), 2));

        Recipe recipeB = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(2), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step B")));
        RecipeId idB = transactionManager.execute(() -> repository.save(recipeB));
        // recipeB has no ratings: denormalized defaults (0, 0.00) apply

        List<RecipeSummaryResponse> summaries = repository.findAllSummaries(new PageRequest(0, 100)).content();

        RecipeSummaryResponse summaryA = summaries.stream()
                .filter(s -> s.id().equals(idA)).findFirst().orElseThrow();
        RecipeSummaryResponse summaryB = summaries.stream()
                .filter(s -> s.id().equals(idB)).findFirst().orElseThrow();

        // Correctness is proven by the fact that seeding ratings directly into DB without calling
        // updateSocialMetrics leaves the denormalized columns unchanged — summaries read them directly.
        assertEquals(0, new BigDecimal("4.50").compareTo(summaryA.averageScore()),
                "average_score for recipe A should be 4.50 (read from denormalized column)");
        assertEquals(2, summaryA.totalRatings(),
                "total_ratings for recipe A should be 2 (read from denormalized column)");
        assertEquals(0, BigDecimal.ZERO.compareTo(summaryB.averageScore()),
                "average_score for recipe B should be 0.00 (no ratings, DEFAULT applied)");
        assertEquals(0, summaryB.totalRatings(),
                "total_ratings for recipe B should be 0");
    }

    @Test
    @DisplayName("findAllSummaries should return the requested page and correct total")
    void findAllSummaries_ShouldReturnCorrectPageAndTotalElements() {
        for (int i = 1; i <= 5; i++) {
            Recipe r = buildRecipe()
                    .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                    .syncSteps(List.of(new RecipeStep(1, "Step " + i)));
            transactionManager.execute(() -> repository.save(r));
        }

        PageResponse<RecipeSummaryResponse> page = repository.findAllSummaries(new PageRequest(0, 2));

        assertEquals(2, page.content().size(), "First page should contain 2 recipes");
        assertEquals(5L, page.totalElements(), "Total should be 5");
        assertEquals(3, page.totalPages(), "There should be 3 pages for 5 elements with page size 2");
    }

    @Test
    @DisplayName("findAllSummaries second page should return remaining records")
    void findAllSummaries_SecondPage_ShouldReturnRemainingRecords() {
        for (int i = 1; i <= 5; i++) {
            Recipe r = buildRecipe()
                    .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                    .syncSteps(List.of(new RecipeStep(1, "Step " + i)));
            transactionManager.execute(() -> repository.save(r));
        }

        PageResponse<RecipeSummaryResponse> lastPage = repository.findAllSummaries(new PageRequest(2, 2));

        assertEquals(1, lastPage.content().size(), "Last page should contain the single remaining record");
        assertEquals(5L, lastPage.totalElements());
    }

    @Test
    @DisplayName("hasUserRatedRecipe should return true only when a user rating exists for the recipe")
    void hasUserRatedRecipe_ShouldReturnTrueOnlyWhenRatingExists() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId recipeId = transactionManager.execute(() -> repository.save(recipe));

        assertFalse(repository.hasUserRatedRecipe(new UserId(2), recipeId),
                "Should return false before voting");

        seedRating(new UserId(2), recipeId, 4);

        assertTrue(repository.hasUserRatedRecipe(new UserId(2), recipeId),
                "Should return true after voting");
        assertFalse(repository.hasUserRatedRecipe(new UserId(3), recipeId),
                "A different user without a vote should return false");
    }

    private void seedRating(UserId userId, RecipeId recipeId, int score) {
        String sql = "INSERT INTO ratings (user_id, recipe_id, score, comment, created_at) VALUES (" +
                userId.value() + ", " + recipeId.value() + ", " + score + ", 'Test comment', NOW())";
        try (Connection conn = dataSource.getConnection(); Statement st = conn.createStatement()) {
            st.execute(sql);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private int queryCount(String sql) {
        try (Connection conn = dataSource.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            rs.next();
            return rs.getInt(1);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private BigDecimal queryBigDecimal(String sql) {
        try (Connection conn = dataSource.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            rs.next();
            return rs.getBigDecimal(1);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Test
    @DisplayName("findById should hydrate the aggregate's media list")
    void findById_ShouldHydrateMediaList() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId recipeId = transactionManager.execute(() -> repository.save(recipe));

        Recipe toUpdate = repository.findById(recipeId).orElseThrow()
                .addMedia(new RecipeMedia(null, recipeId, "key/main.jpg", "LOCAL", "image/jpeg", 204800L, true,  0))
                .addMedia(new RecipeMedia(null, recipeId, "key/extra.png", "LOCAL", "image/png",  102400L, false, 1));
        transactionManager.execute(() -> repository.update(toUpdate));

        Recipe loaded = repository.findById(recipeId).orElseThrow();

        assertEquals(2, loaded.getMediaItems().size(), "Should hydrate exactly 2 media items");
        RecipeMedia main = loaded.getMediaItems().stream().filter(RecipeMedia::isMain).findFirst().orElseThrow();
        RecipeMedia extra = loaded.getMediaItems().stream().filter(m -> !m.isMain()).findFirst().orElseThrow();

        assertEquals("key/main.jpg", main.storageKey());
        assertEquals("LOCAL", main.storageProvider());
        assertEquals("image/jpeg", main.mimeType());
        assertEquals(204800L, main.sizeBytes());
        assertEquals(0, main.sortOrder());

        assertEquals("key/extra.png", extra.storageKey());
        assertEquals(1, extra.sortOrder());
    }

    @Test
    @DisplayName("update should apply smart-diff: insert, update, and delete media items")
    void update_ShouldSmartDiffMedia() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId recipeId = transactionManager.execute(() -> repository.save(recipe));

        Recipe toUpdate = repository.findById(recipeId).orElseThrow()
                .addMedia(new RecipeMedia(null, recipeId, "key/a.jpg", "LOCAL", "image/jpeg", 100L, true,  0))
                .addMedia(new RecipeMedia(null, recipeId, "key/b.jpg", "LOCAL", "image/jpeg", 200L, false, 1));
        transactionManager.execute(() -> repository.update(toUpdate));

        Recipe afterFirst = repository.findById(recipeId).orElseThrow();
        assertEquals(2, afterFirst.getMediaItems().size());

        RecipeMediaId idA = afterFirst.getMediaItems().stream().filter(RecipeMedia::isMain).findFirst().orElseThrow().id();
        RecipeMediaId idB = afterFirst.getMediaItems().stream().filter(m -> !m.isMain()).findFirst().orElseThrow().id();

        // Swap main + add new item, remove A
        Recipe toPersist = afterFirst
                .setMainMedia(idB)
                .removeMedia(idA)
                .addMedia(new RecipeMedia(null, recipeId, "key/c.jpg", "LOCAL", "image/png", 300L, false, 2));
        transactionManager.execute(() -> repository.update(toPersist));

        Recipe final_ = repository.findById(recipeId).orElseThrow();

        assertEquals(2, final_.getMediaItems().size(), "Should have 2 items after diff");
        assertTrue(final_.getMediaItems().stream().anyMatch(m -> "key/b.jpg".equals(m.storageKey()) && m.isMain()),
                "key/b.jpg should now be main");
        assertTrue(final_.getMediaItems().stream().anyMatch(m -> "key/c.jpg".equals(m.storageKey())),
                "key/c.jpg should have been inserted");
        assertFalse(final_.getMediaItems().stream().anyMatch(m -> "key/a.jpg".equals(m.storageKey())),
                "key/a.jpg should have been deleted");
    }

    @Test
    @DisplayName("findAllSummaries should return the correct mainMediaStorageKey when the recipe has a main image")
    void findAllSummaries_ShouldReturnMainMediaStorageKey_WhenRecipeHasMainImage() {
        Recipe recipe = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step 1")));
        RecipeId recipeId = transactionManager.execute(() -> repository.save(recipe));

        Recipe toUpdate = repository.findById(recipeId).orElseThrow()
                .addMedia(new RecipeMedia(null, recipeId, "media/thumbnail.jpg", "LOCAL", "image/jpeg", 51200L, true, 0));
        transactionManager.execute(() -> repository.update(toUpdate));

        List<RecipeSummaryResponse> summaries = repository.findAllSummaries(new PageRequest(0, 100)).content();
        RecipeSummaryResponse summary = summaries.stream()
                .filter(s -> s.id().equals(recipeId)).findFirst().orElseThrow();

        assertEquals("media/thumbnail.jpg", summary.mainMediaStorageKey(),
                "mainMediaStorageKey should match the storage_key of the main image");
    }

    @Test
    @DisplayName("findAllSummaries should include recipes without media (LEFT JOIN: null mainMediaStorageKey)")
    void findAllSummaries_ShouldIncludeRecipesWithoutMedia_WithNullStorageKey() {
        Recipe withMedia = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(1), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step A")));
        RecipeId idWithMedia = transactionManager.execute(() -> repository.save(withMedia));
        Recipe withMediaToUpdate = repository.findById(idWithMedia).orElseThrow()
                .addMedia(new RecipeMedia(null, idWithMedia, "media/img.jpg", "LOCAL", "image/jpeg", 1024L, true, 0));
        transactionManager.execute(() -> repository.update(withMediaToUpdate));

        Recipe noMedia = buildRecipe()
                .syncIngredients(List.of(new RecipeIngredient(new IngredientId(2), new UnitId(1), BigDecimal.ONE)))
                .syncSteps(List.of(new RecipeStep(1, "Step B")));
        RecipeId idNoMedia = transactionManager.execute(() -> repository.save(noMedia));

        List<RecipeSummaryResponse> summaries = repository.findAllSummaries(new PageRequest(0, 100)).content();

        RecipeSummaryResponse withMediaSummary = summaries.stream()
                .filter(s -> s.id().equals(idWithMedia)).findFirst().orElseThrow();
        RecipeSummaryResponse noMediaSummary = summaries.stream()
                .filter(s -> s.id().equals(idNoMedia)).findFirst().orElseThrow();

        assertEquals("media/img.jpg", withMediaSummary.mainMediaStorageKey(),
                "Recipe with image should expose its storage_key");
        assertNull(noMediaSummary.mainMediaStorageKey(),
                "Recipe without image should return null (LEFT JOIN produces no row)");
        assertEquals(2L, summaries.stream()
                .filter(s -> s.id().equals(idWithMedia) || s.id().equals(idNoMedia)).count(),
                "Both recipes should appear in the listing");
    }

    private BigDecimal queryQuantity(int recipeId, int ingredientId) {
        String sql = "SELECT quantity FROM recipe_ingredients WHERE recipe_id = " + recipeId + " AND ingredient_id = " + ingredientId;
        try (Connection conn = dataSource.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getBigDecimal("quantity") : null;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
